"""empty message

Revision ID: 115092440e4d
Revises: 7892bcafbb83
Create Date: 2017-07-30 09:50:03.509114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115092440e4d'
down_revision = '7892bcafbb83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follwer_id', sa.Integer(), nullable=False),
    sa.Column('follwed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['follwed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follwer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follwer_id', 'follwed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follows')
    # ### end Alembic commands ###
