"""empty message

Revision ID: 300562d80424
Revises: 07b733665c7c
Create Date: 2017-08-03 15:01:43.462854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300562d80424'
down_revision = '07b733665c7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('about_me_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'about_me_html')
    # ### end Alembic commands ###
