"""empty message

Revision ID: 7892bcafbb83
Revises: a3a99430c04e
Create Date: 2017-07-29 21:52:46.507219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7892bcafbb83'
down_revision = 'a3a99430c04e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'text_html')
    # ### end Alembic commands ###
