"""empty message

Revision ID: ba4423f58257
Revises: ed0d12e9217b
Create Date: 2017-08-04 10:49:26.815355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba4423f58257'
down_revision = 'ed0d12e9217b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_avatar', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'real_avatar')
    # ### end Alembic commands ###
