"""empty message

Revision ID: ea3dbeaa39ad
Revises: 115092440e4d
Create Date: 2017-07-30 09:53:07.695344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ea3dbeaa39ad'
down_revision = '115092440e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('followed_id', sa.Integer(), nullable=False))
    op.add_column('follows', sa.Column('follower_id', sa.Integer(), nullable=False))
    op.drop_constraint(u'follows_ibfk_2', 'follows', type_='foreignkey')
    op.drop_constraint(u'follows_ibfk_1', 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.drop_column('follows', 'follwer_id')
    op.drop_column('follows', 'follwed_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('follwed_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('follows', sa.Column('follwer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(u'follows_ibfk_1', 'follows', 'users', ['follwed_id'], ['id'])
    op.create_foreign_key(u'follows_ibfk_2', 'follows', 'users', ['follwer_id'], ['id'])
    op.drop_column('follows', 'follower_id')
    op.drop_column('follows', 'followed_id')
    # ### end Alembic commands ###
