"""empty message

Revision ID: ed0d12e9217b
Revises: 300562d80424
Create Date: 2017-08-03 21:18:24.575690

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed0d12e9217b'
down_revision = '300562d80424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'text_html')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text_html', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
